name: Auto Update IPTV

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # BẮT BUỘC: Cấp quyền ghi dữ liệu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Cập nhật lên v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Cập nhật lên v4
        with:
          node-version: '20'

      - name: Run script
        run: node iptv.js

      - name: Commit and push file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kkphim.m3u
          git commit -m "Auto update: $(date)" || exit 0
          git push
